name: sen1511-gurobi
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.10
    - pyomo=6.4.1
    - pandas=1.4.3
    - matplotlib
    - jupyter
    - glpk
    - gurobi
    - pip
    - pip:
        - -e git+https://github.com/sjpfenninger/sen1511.git#egg=sen1511utils&subdirectory=sen1511utils